server {
    listen       80;
    server_name  localhost;

    resolver kube-dns.kube-system.svc.cluster.local;
    set $plausible_host  plausible.computational.bio.uni-giessen.de;
    set $plausible_script pa-UIrN-ZtAp-8_NzUqLRxvW.js;
    set $plausible_script_url https://$plausible_host/js/$plausible_script;
    set $plausible_event_url https://$plausible_host/api/event;
    
    location ~* (.gz)$ {
        root   /usr/share/nginx/html;
        add_header Content-Encoding gzip;
    }

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index index.html index.htm;
    }

    location = /js/script.js {
        proxy_pass $plausible_script_url;
        proxy_set_header Host $plausible_host;
    }

    location = /api/event {
        proxy_pass $plausible_event_url;
        proxy_set_header Host $plausible_host;
        proxy_buffering on;
        proxy_http_version 1.1;

        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }
    
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}